name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      # Especifica NX_BASE y NX_HEAD para nx affected
      - run: |
          export NX_BASE=origin/main
          export NX_HEAD=$(git rev-parse HEAD)
          npx nx affected --target=lint test build
